name: http_logger
description: A logging middleware for Dart's http module.
version: 1.0.0
author: Gurleen Sethi <sarusethi@rocketmail.com>
homepage: http://www.github.com/gurleensethi

dependencies:
  http_middleware:
    git: https://github.com/safarmer/http_middleware.git

environment:
  sdk: ">=2.7.0 <3.0.0"
